### ISSUE TITLE
Flexiv Hardware Undefined symbol

### ISSUE THREAD

**Issue by Maxime-Syc** [flexivrobotics/flexiv_ros2#15]
Hello everyone,

I am trying to connect to the Flexiv controller via the rizon.launch.py launch file. However, launching with the command `ros2 launch flexiv_bringup rizon.launch.py robot_ip:=192.168.2.100 local_ip:=192.168.2.106 robot_controller:=rizon_arm_controller start_rviz:=false` I get the following error from `ros2_control_node-1`:

```
[ros2_control_node-1] /opt/ros/foxy/lib/controller_manager/ros2_control_node: symbol lookup error: /ros-flexiv_ws/install/flexiv_hardware/lib/libflexiv_hardware.so: undefined symbol: _ZN6flexiv5RobotC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_
[ERROR] [ros2_control_node-1]: process has died [pid 2567, exit code 127, cmd '/opt/ros/foxy/lib/controller_manager/ros2_control_node --ros-args --params-file /tmp/launch_params_lwng52a_ --params-file /ros-flexiv_ws/install/flexiv_bringup/share/flexiv_bringup/config/rizon_controllers.yaml'].
```

I am running the package inside a docker container based on the ros:foxy image on a Jetson AGX Orin dev kit. The container has been started with the --network host setting and I am mounting my workspace as a bind volume.

Here is the Dockerfile for reproduction

```
FROM ros:foxy

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
    python3-rosdep2 \
    ros-$ROS_DISTRO-ros2-control \
    ros-$ROS_DISTRO-control-toolbox \
    ros-$ROS_DISTRO-moveit \
    ros-$ROS_DISTRO-ros2-controllers \
    ros-$ROS_DISTRO-test-msgs \
    ros-$ROS_DISTRO-rmw-cyclonedds-cpp

ENV RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

RUN mkdir -p /ros-flexiv_ws/src

WORKDIR /ros-flexiv_ws

COPY ros_entrypoint.sh /ros_entrypoint.sh

CMD ["sleep", "infinity"]
```

The referenced ros_entrypoint.sh script is a custom entrypoint that installs dependencies at start time

```
#!/bin/bash
set -e

# setup ros2 environment
echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> ~/.bashrc
source /opt/ros/${ROS_DISTRO}/setup.bash

sudo apt-get update
rosdep update

# install workspace dependencies
rosdep install --from-path src -y --ignore-src

$@
```

My workspace only contains the flexiv_ros2 repository in the src folder.

Here is the full log from the console :

```
[INFO] [launch]: All log files can be found below /root/.ros/log/2023-06-16-16-18-30-507546-[machine name]-2563
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [ros2_control_node-1]: process started with pid [2567]
[INFO] [robot_state_publisher-2]: process started with pid [2569]
[INFO] [spawner.py-3]: process started with pid [2571]
[INFO] [ros2 run controller_manager spawner.py joint_state_broadcaster-4]: process started with pid [2573]
[INFO] [ros2 run controller_manager spawner.py force_torque_sensor_broadcaster-5]: process started with pid [2575]
[INFO] [ros2 run controller_manager spawner.py external_wrench_in_base_broadcaster-6]: process started with pid [2578]
[INFO] [ros2 run controller_manager spawner.py external_wrench_in_tcp_broadcaster-7]: process started with pid [2581]
[INFO] [ros2 run controller_manager spawner.py tcp_pose_state_broadcaster-8]: process started with pid [2583]
[ros2_control_node-1] 1686932311.144371 [0] ros2_contr: using network interface wlan0 (udp/192.168.10.135) selected arbitrarily from: wlan0, docker0, eth1
[robot_state_publisher-2] 1686932311.152398 [0] robot_stat: using network interface wlan0 (udp/192.168.10.135) selected arbitrarily from: wlan0, docker0, eth1
[ros2_control_node-1] [INFO] [1686932311.163628471] [FlexivHardwareInterface]: Connecting to robot at "192.168.2.100" from "192.168.2.106" ...
[ros2_control_node-1] /opt/ros/foxy/lib/controller_manager/ros2_control_node: symbol lookup error: /ros-flexiv_ws/install/flexiv_hardware/lib/libflexiv_hardware.so: undefined symbol: _ZN6flexiv5RobotC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_
[ERROR] [ros2_control_node-1]: process has died [pid 2567, exit code 127, cmd '/opt/ros/foxy/lib/controller_manager/ros2_control_node --ros-args --params-file /tmp/launch_params_lwng52a_ --params-file /ros-flexiv_ws/install/flexiv_bringup/share/flexiv_bringup/config/rizon_controllers.yaml'].
[INFO] [launch]: process[ros2_control_node-1] was required: shutting down launched system
[robot_state_publisher-2] Parsing robot urdf xml string.
[robot_state_publisher-2] Link base_link had 1 children
[robot_state_publisher-2] Link link1 had 1 children
[robot_state_publisher-2] Link link2 had 1 children
[robot_state_publisher-2] Link link3 had 1 children
[robot_state_publisher-2] Link link4 had 1 children
[robot_state_publisher-2] Link link5 had 1 children
[robot_state_publisher-2] Link link6 had 1 children
[robot_state_publisher-2] Link link7 had 1 children
[robot_state_publisher-2] Link flange had 0 children
[robot_state_publisher-2] [INFO] [1686932311.170109931] [robot_state_publisher]: got segment base_link
[robot_state_publisher-2] [INFO] [1686932311.170323727] [robot_state_publisher]: got segment flange
[robot_state_publisher-2] [INFO] [1686932311.170352016] [robot_state_publisher]: got segment link1
[robot_state_publisher-2] [INFO] [1686932311.170365584] [robot_state_publisher]: got segment link2
[robot_state_publisher-2] [INFO] [1686932311.170376560] [robot_state_publisher]: got segment link3
[robot_state_publisher-2] [INFO] [1686932311.170387344] [robot_state_publisher]: got segment link4
[robot_state_publisher-2] [INFO] [1686932311.170397744] [robot_state_publisher]: got segment link5
[robot_state_publisher-2] [INFO] [1686932311.170408113] [robot_state_publisher]: got segment link6
[robot_state_publisher-2] [INFO] [1686932311.170418641] [robot_state_publisher]: got segment link7
[robot_state_publisher-2] [INFO] [1686932311.170428913] [robot_state_publisher]: got segment world
[INFO] [ros2 run controller_manager spawner.py tcp_pose_state_broadcaster-8]: sending signal 'SIGINT' to process[ros2 run controller_manager spawner.py tcp_pose_state_broadcaster-8]
[INFO] [ros2 run controller_manager spawner.py external_wrench_in_tcp_broadcaster-7]: sending signal 'SIGINT' to process[ros2 run controller_manager spawner.py external_wrench_in_tcp_broadcaster-7]
[INFO] [ros2 run controller_manager spawner.py external_wrench_in_base_broadcaster-6]: sending signal 'SIGINT' to process[ros2 run controller_manager spawner.py external_wrench_in_base_broadcaster-6]
[INFO] [ros2 run controller_manager spawner.py force_torque_sensor_broadcaster-5]: sending signal 'SIGINT' to process[ros2 run controller_manager spawner.py force_torque_sensor_broadcaster-5]
[INFO] [ros2 run controller_manager spawner.py joint_state_broadcaster-4]: sending signal 'SIGINT' to process[ros2 run controller_manager spawner.py joint_state_broadcaster-4]
[INFO] [spawner.py-3]: sending signal 'SIGINT' to process[spawner.py-3]
[INFO] [robot_state_publisher-2]: sending signal 'SIGINT' to process[robot_state_publisher-2]
[spawner.py-3] Traceback (most recent call last):
[spawner.py-3]   File "/opt/ros/foxy/lib/controller_manager/spawner.py", line 23, in <module>
[spawner.py-3]     from controller_manager import configure_controller, list_controllers, \
[spawner.py-3]   File "/opt/ros/foxy/lib/python3.8/site-packages/controller_manager/__init__.py", line 15, in <module>
[spawner.py-3]     from .controller_manager_services import (
[spawner.py-3]   File "/opt/ros/foxy/lib/python3.8/site-packages/controller_manager/controller_manager_services.py", line 15, in <module>
[spawner.py-3]     from controller_manager_msgs.srv import ConfigureController, \
[spawner.py-3]   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
[spawner.py-3]   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
[spawner.py-3]   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
[spawner.py-3]   File "<frozen importlib._bootstrap_external>", line 844, in exec_module
[spawner.py-3]   File "<frozen importlib._bootstrap_external>", line 980, in get_code
[spawner.py-3]   File "<frozen importlib._bootstrap_external>", line 1037, in get_data
[spawner.py-3] KeyboardInterrupt
[robot_state_publisher-2] [INFO] [1686932311.191987413] [rclcpp]: signal_handler(signal_value=2)
[ERROR] [spawner.py-3]: process has died [pid 2571, exit code -2, cmd '/opt/ros/foxy/lib/controller_manager/spawner.py rizon_arm_controller -c /controller_manager --ros-args'].
[ros2 run controller_manager spawner.py tcp_pose_state_broadcaster-8] 1686932311.683512 [0]    python3: using network interface wlan0 (udp/192.168.10.135) selected arbitrarily from: wlan0, docker0, eth1
[ros2 run controller_manager spawner.py joint_state_broadcaster-4] 1686932311.683512 [0]    python3: using network interface wlan0 (udp/192.168.10.135) selected arbitrarily from: wlan0, docker0, eth1
[ros2 run controller_manager spawner.py external_wrench_in_tcp_broadcaster-7] 1686932311.683516 [0]    python3: using network interface wlan0 (udp/192.168.10.135) selected arbitrarily from: wlan0, docker0, eth1
[ros2 run controller_manager spawner.py external_wrench_in_base_broadcaster-6] 1686932311.683516 [0]    python3: using network interface wlan0 (udp/192.168.10.135) selected arbitrarily from: wlan0, docker0, eth1
[ros2 run controller_manager spawner.py force_torque_sensor_broadcaster-5] 1686932311.683532 [0]    python3: using network interface wlan0 (udp/192.168.10.135) selected arbitrarily from: wlan0, docker0, eth1
[ros2 run controller_manager spawner.py force_torque_sensor_broadcaster-5] [INFO] [1686932311.771025809] [spawner_force_torque_sensor_broadcaster]: Waiting for /controller_manager services
[ros2 run controller_manager spawner.py external_wrench_in_tcp_broadcaster-7] [INFO] [1686932311.771038993] [spawner_external_wrench_in_tcp_broadcaster]: Waiting for /controller_manager services
[ros2 run controller_manager spawner.py joint_state_broadcaster-4] [INFO] [1686932311.771040817] [spawner_joint_state_broadcaster]: Waiting for /controller_manager services
[ros2 run controller_manager spawner.py external_wrench_in_base_broadcaster-6] [INFO] [1686932311.771417496] [spawner_external_wrench_in_base_broadcaster]: Waiting for /controller_manager services
[ros2 run controller_manager spawner.py tcp_pose_state_broadcaster-8] [INFO] [1686932311.771535034] [spawner_tcp_pose_state_broadcaster]: Waiting for /controller_manager services
[INFO] [robot_state_publisher-2]: process has finished cleanly [pid 2569]
[ros2 run controller_manager spawner.py external_wrench_in_base_broadcaster-6] [INFO] [1686932313.790227002] [spawner_external_wrench_in_base_broadcaster]: Waiting for /controller_manager services
[ros2 run controller_manager spawner.py tcp_pose_state_broadcaster-8] [INFO] [1686932313.790242779] [spawner_tcp_pose_state_broadcaster]: Waiting for /controller_manager services
[ros2 run controller_manager spawner.py external_wrench_in_tcp_broadcaster-7] [INFO] [1686932313.790459935] [spawner_external_wrench_in_tcp_broadcaster]: Waiting for /controller_manager services
[ros2 run controller_manager spawner.py force_torque_sensor_broadcaster-5] [INFO] [1686932313.790478463] [spawner_force_torque_sensor_broadcaster]: Waiting for /controller_manager services
[ros2 run controller_manager spawner.py joint_state_broadcaster-4] [INFO] [1686932313.790570177] [spawner_joint_state_broadcaster]: Waiting for /controller_manager services
[ros2 run controller_manager spawner.py external_wrench_in_tcp_broadcaster-7] [INFO] [1686932315.811551531] [spawner_external_wrench_in_tcp_broadcaster]: Waiting for /controller_manager services
[ros2 run controller_manager spawner.py tcp_pose_state_broadcaster-8] [INFO] [1686932315.811663789] [spawner_tcp_pose_state_broadcaster]: Waiting for /controller_manager services
[ros2 run controller_manager spawner.py external_wrench_in_base_broadcaster-6] [INFO] [1686932315.811725198] [spawner_external_wrench_in_base_broadcaster]: Waiting for /controller_manager services
[ros2 run controller_manager spawner.py joint_state_broadcaster-4] [INFO] [1686932315.812004627] [spawner_joint_state_broadcaster]: Waiting for /controller_manager services
[ros2 run controller_manager spawner.py force_torque_sensor_broadcaster-5] [INFO] [1686932315.812160150] [spawner_force_torque_sensor_broadcaster]: Waiting for /controller_manager services
[ERROR] [ros2 run controller_manager spawner.py tcp_pose_state_broadcaster-8]: process[ros2 run controller_manager spawner.py tcp_pose_state_broadcaster-8] failed to terminate '5' seconds after receiving 'SIGINT', escalating to 'SIGTERM'
[ERROR] [ros2 run controller_manager spawner.py external_wrench_in_tcp_broadcaster-7]: process[ros2 run controller_manager spawner.py external_wrench_in_tcp_broadcaster-7] failed to terminate '5' seconds after receiving 'SIGINT', escalating to 'SIGTERM'
[ERROR] [ros2 run controller_manager spawner.py external_wrench_in_base_broadcaster-6]: process[ros2 run controller_manager spawner.py external_wrench_in_base_broadcaster-6] failed to terminate '5' seconds after receiving 'SIGINT', escalating to 'SIGTERM'
[INFO] [ros2 run controller_manager spawner.py tcp_pose_state_broadcaster-8]: sending signal 'SIGTERM' to process[ros2 run controller_manager spawner.py tcp_pose_state_broadcaster-8]
[ERROR] [ros2 run controller_manager spawner.py force_torque_sensor_broadcaster-5]: process[ros2 run controller_manager spawner.py force_torque_sensor_broadcaster-5] failed to terminate '5' seconds after receiving 'SIGINT', escalating to 'SIGTERM'
[ERROR] [ros2 run controller_manager spawner.py joint_state_broadcaster-4]: process[ros2 run controller_manager spawner.py joint_state_broadcaster-4] failed to terminate '5' seconds after receiving 'SIGINT', escalating to 'SIGTERM'
[ERROR] [ros2 run controller_manager spawner.py tcp_pose_state_broadcaster-8]: process has died [pid 2583, exit code -15, cmd 'ros2 run controller_manager spawner.py tcp_pose_state_broadcaster'].
[INFO] [ros2 run controller_manager spawner.py external_wrench_in_tcp_broadcaster-7]: sending signal 'SIGTERM' to process[ros2 run controller_manager spawner.py external_wrench_in_tcp_broadcaster-7]
[INFO] [ros2 run controller_manager spawner.py external_wrench_in_base_broadcaster-6]: sending signal 'SIGTERM' to process[ros2 run controller_manager spawner.py external_wrench_in_base_broadcaster-6]
[INFO] [ros2 run controller_manager spawner.py force_torque_sensor_broadcaster-5]: sending signal 'SIGTERM' to process[ros2 run controller_manager spawner.py force_torque_sensor_broadcaster-5]
[ERROR] [ros2 run controller_manager spawner.py external_wrench_in_tcp_broadcaster-7]: process has died [pid 2581, exit code -15, cmd 'ros2 run controller_manager spawner.py external_wrench_in_tcp_broadcaster'].
[ERROR] [ros2 run controller_manager spawner.py external_wrench_in_base_broadcaster-6]: process has died [pid 2578, exit code -15, cmd 'ros2 run controller_manager spawner.py external_wrench_in_base_broadcaster'].
[INFO] [ros2 run controller_manager spawner.py joint_state_broadcaster-4]: sending signal 'SIGTERM' to process[ros2 run controller_manager spawner.py joint_state_broadcaster-4]
[ERROR] [ros2 run controller_manager spawner.py force_torque_sensor_broadcaster-5]: process has died [pid 2575, exit code -15, cmd 'ros2 run controller_manager spawner.py force_torque_sensor_broadcaster'].
[ERROR] [ros2 run controller_manager spawner.py joint_state_broadcaster-4]: process has died [pid 2573, exit code -15, cmd 'ros2 run controller_manager spawner.py joint_state_broadcaster'].
```

I am using console log because the log file created by ROS dows not include the undefined symbol error

Thank you for any help you can give me.

**Comment by Maxime-Syc** [comment]
I used `c++filt` to demangle  `_ZN6flexiv5RobotC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_`
This returns
`flexiv::Robot::Robot(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)`

**Comment by Maxime-Syc** [comment]
Follow-up, I tested the same sequence on an x86-64 computer and there was no error, so this seems to be a problem with arm64

**Comment by munseng-flexiv** [comment]
Hi @Maxime-Syc,

the error is due to the RDK static library being set wrongly for Linux arm64. I have created a PR to fix this issue.
